spring:
  kafka:
    topic:
      name: ${KAFKA_TOPIC_NAME:reddogoct3}
      group: ${KAFKA_TOPIC_GROUP:order-service}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        sasl:
          mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
          jaas:
            config: ${KAFKA_SASL_JAAS_CONFIG}
        spring:
          json:
            type:
              mapping: ordersummary:com.microsoft.gbb.rasa.orderservice.dto.OrderSummaryDto
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USER}
    url: ${MYSQL_URL}
  flyway:
    baseline-on-migrate: 'true'
  banner:
    location: static/banner.txt
eureka:
  client:
    register-with-eureka: 'false'
    fetch-registry: 'false'
springdoc:
  swagger-ui:
    enabled: 'true'
    path: /swagger
  api-docs:
    path: /api-docs
topic:
  name:
    producer: ${KAFKA_TOPIC_NAME:reddogoct3}
server:
  port: '8082'
